### PR TITLE
Fluid: Reposition and rescale

### PR DESCRIPTION
**Pull request by etorth**
Continuation of #481

### CODE REVIEW

**Comment by MatthiasWM** [comment]
Sorry for the very late reply. 

OK, so I see what you are doing here, and I believe that we can do a much easier implementation. If you set relative position, the Widget Class is generate at 0, 0 first and later moved, so the Fl_Group::position() method does all the work. We can do the same for resizing. We just let Fl_Group::resize() do all the work for us. So these would be the code snippets for all three options:

Default:
```
UserInterface::UserInterface(int X, int Y, int W, int H, const char *L) :
  Fl_Group(X, Y, W, H, L)
{
  { new Fl_Button(20, 20, 63, 20, "button");
  } // Fl_Button* o
  end();
}
```

Position relative:
```
UserInterface::UserInterface(int X, int Y, int W, int H, const char *L) :
  Fl_Group(0, 0, W, H, L)
{
  { new Fl_Button(20, 20, 63, 20, "button");
  } // Fl_Button* o
  position(X, Y);
  end();
}
```

Position and size relative:
```
UserInterface::UserInterface(int X, int Y, int W, int H, const char *L) :
  Fl_Group(0, 0, 329, 224, L)  // 329 and 224 is the original size from Fluid
{
  { new Fl_Button(20, 20, 63, 20, "button");
  } // Fl_Button* o
  resize(X, Y, W, H);
  end();
}
```

Please let me know if this solves your issues.

**Comment by etorth** [comment]
It won't work if your embedded widgets has larger size than embedding widget.


> Sorry for the very late reply.
> 
> OK, so I see what you are doing here, and I believe that we can do a much easier implementation. If you set relative position, the Widget Class is generate at 0, 0 first and later moved, so the Fl_Group::position() method does all the work. We can do the same for resizing. We just let Fl_Group::resize() do all the work for us. So these would be the code snippets for all three options:
> 
> Default:
> 
> ```
> UserInterface::UserInterface(int X, int Y, int W, int H, const char *L) :
>   Fl_Group(X, Y, W, H, L)
> {
>   { new Fl_Button(20, 20, 63, 20, "button");
>   } // Fl_Button* o
>   end();
> }
> ```
> 
> Position relative:
> 
> ```
> UserInterface::UserInterface(int X, int Y, int W, int H, const char *L) :
>   Fl_Group(0, 0, W, H, L)
> {
>   { new Fl_Button(20, 20, 63, 20, "button");
>   } // Fl_Button* o
>   position(X, Y);
>   end();
> }
> ```
> 
> Position and size relative:
> 
> ```
> UserInterface::UserInterface(int X, int Y, int W, int H, const char *L) :
>   Fl_Group(0, 0, 329, 224, L)  // 329 and 224 is the original size from Fluid
> {
>   { new Fl_Button(20, 20, 63, 20, "button");
>   } // Fl_Button* o
>   resize(X, Y, W, H);
>   end();
> }
> ```
> 
> Please let me know if this solves your issues.

**Comment by MatthiasWM** [comment]
Why not? The `resize()` will update your embedded window to fit to the requested size, resizing all its children as well. Maybe I am missing something here. The original message had sample code. Could you please post a .fl where original Fluid generates code that does not work for you, so I can try out my approach? Thanks!

> It won't work if your embedded widgets has larger size than embedding widget.
> 
> > Position and size relative:
> > ```
> >   ...
> >   resize(X, Y, W, H);
> >   ...
> > ```

**Comment by Albrecht-S** [comment]
> Could you please post a .fl where original Fluid generates code that does not work for you, so I can try out my approach?

@MatthiasWM On behalf of the OP, it's all there.
1. The original test.fl file is inlined in this https://github.com/fltk/fltk/pull/481#issuecomment-1214219738
2. My modified .fl file can be found as a link in this https://github.com/fltk/fltk/pull/481#issuecomment-1214401757 together with my notes what was "wrong" in the original file (widget sizes). Direct link: [pr-481_resize_rescale_v3.fl.txt](https://github.com/fltk/fltk/files/9333563/pr-481_resize_rescale_v3.fl.txt)

I just tested both `.fl` files with current `fluid` and you can easily see the difference. Obviously the OP's proposal is intended to "fix" the code generated by `fluid` from their original `test.fl` file so it works like the file modified by me.

The discussion continued in https://github.com/fltk/fltk/pull/481#issuecomment-1214443071 where @etorth explained why his patch would be useful because you can't always "know" the exact size of a "class definition" if it has been developed in another project or by another team.

@MatthiasWM That said, I'm not sure if it's worth the effort and I wasn't sure whether the proposed code would be correct. That's why I asked for your review. I'm +/- 0 on this change and would like to leave the decision to you.

**Comment by MatthiasWM** [comment]
@etorth @Albrecht-S Ok, so I implemented the feature in PR #531 . The implementation works as expected with the give .fl file, and I am pretty sure it will work well for other cases too. It's actually a nice feature that makes widget classes more useful.

**Pull request closed without merging**
