### PR TITLE
Refactor code to make rounded rectangles accessible

### PR DESCRIPTION
**Pull request by MatthiasWM**
This adds fl_rrect and fl_rrectf (note the additional `r`) so the user can draw rounded rectangles. This uses existing and optimised code that is rearranged.

As mentioned in issue #262, we already implemented drawing code for rounded rectangles, but we did not have an API to access the code besides via box types. I also optimised to code to ignore drawing matrices, do a faster lookup, and avoid searching the graphics driver multiple times.

### CODE REVIEW

**Comment by Albrecht-S** [comment]
> This adds `fl_rrect` and `fl_rrectf` (note the additional r) ...

I didn't look at the code yet, but IMHO these function names can too easily be confused with their "normal" drawing functions (which might cause long searches for coding errors).

Can we please change the function names to `fl_round[ed]_rect()` and `fl_round[ed]_rectf()` or other names that are better to distinguish?

**Comment by Albrecht-S** [comment]
Regarding requested name changes: I believe it's important for the public API but it would be helpful to change the internal driver function names as well to remain consistent.

**Comment by MatthiasWM** [comment]
The internal naming absolutely should reflect the public API. Fixed that.

**Comment by Albrecht-S** [comment]
Note: I pushed a commit to your PR (branch) to remove an unused variable.

Tested with test/boxtype, rounded boxes still look fine. I didn't test explicitly calling the new functions though. Anyway, +1 from me.

**Pull request merged**
