### PR TITLE
Fl_Flex updates

### PR DESCRIPTION
**Pull request by Albrecht-S**
See discussion in fltk.coredev, thread ["Fl_Flex method name question"](https://groups.google.com/g/fltkcoredev/c/0pHCzc9m0eI/m/a5FUpouMBAAJ).

Please note that this branch also changes fluid in an incompatible way, i.e. besides changing the code I also changed the .fl file syntax. More below...

### CODE REVIEW

**Comment by Albrecht-S** [comment]
Further options we might want to consider (according to the thread in fltk.coredev):
- Allow fixed size `0` and use `-1` (negative) for changing a widget back to `flexible`
- add a size() method that returns the current width or height depending on type() (horizontal or vertical)
- add new methods:
  - `int flexible(Fl_Widget *) const` to query whether a widget is flexible or fixed
  - `void flexible(Fl_Widget *, int)` to set a widget flexible (1) or fixed (0)

I'm not really keen on adding these `flexible()` methods but anyway, here they are as an option.

**Comment by Albrecht-S** [comment]
@MatthiasWM Regarding `fluid`: I changed
```diff
-  "set_size_tuples" <word> : this Word is written with printf "{%d", where %d
+  "fixed_size_tuples" <word> : this Word is written with printf "{%d", where %d
```
in `fluid/README_fl.txt` and in `fluid/Fl_Group_Type.cxx`. I did this for consistency but this is disputable. It would break existing `fluid` (`.fl`) files that have been created with the unreleased 1.4.0 fluid.

**Comment by Albrecht-S** [comment]
@MatthiasWM Hmm, any more info than "thanks"? Maybe ...
- [ ] OK, yes, please merge
- [ ] I'll review later
- [ ] There are things I'd like to be changed ...

I know it's not easy to decide, sorry for asking for further info.

**Comment by MatthiasWM** [comment]
Sorry, busy day at work today. I'll probably get to review this tonight.

**Comment by MatthiasWM** [comment]
Thanks for also fixing FLUID and the comments. I like it.

**Comment by Albrecht-S** [comment]
Welcome, thanks for checking. Merged.

**Pull request merged**
