### PR TITLE
Submenus with no callback enter their submenu instead of closing the whole menu

### PR DESCRIPTION
**Pull request by dannye**
Based on discussion in #1041

This PR includes the following changes:

1. Keep the menu open if a submenu with no callback is clicked.
   - This change was applied to both the FLTK menubar and the Mac sys menubar.
3. Enter the submenu if Enter or Space is hit on a submenu with no callback.
   - This change was only applied to the FLTK menubar. This is already the behavior of the Mac sys menubar.

These modifications are not applied to top-level menubar menu items, so Enter, Space, and mouse click still toggle the menu for top-level items.

I think this is more user-friendly, and is pretty common among menu systems, including the Mac sys menubar.

Apply this patch to test/menubar.cxx to test out a submenu _with_ a callback (can easily be tested with both the FLTK menubar and the Mac sys menubar):

```diff
diff --git a/test/menubar.cxx b/test/menubar.cxx
index a0424732d..fba4d6aa5 100644
--- a/test/menubar.cxx
+++ b/test/menubar.cxx
@@ -56,6 +56,10 @@ void test_cb(Fl_Widget* w, void*) {
     G_tty->printf("%s\n", m->label());
 }
 
+void test_cb2(Fl_Widget* w, void*) {
+  G_tty->printf("Submenu test\n");
+}
+
 void quit_cb(Fl_Widget*, void*) {exit(0);}
 
 Fl_Menu_Item hugemenu[100];
@@ -84,7 +88,7 @@ Fl_Menu_Item menutable[] = {
     {"shortcut",FL_ALT+FL_SHIFT+FL_F+1},
     {"shortcut",FL_ALT+FL_CTRL+FL_F+1},
     {"shortcut",FL_ALT+FL_SHIFT+FL_CTRL+FL_F+1, 0,0, FL_MENU_DIVIDER},
-    {"&Submenus", FL_ALT+'S',   0, (void*)"Submenu1", FL_SUBMENU},
+    {"&Submenus", FL_ALT+'S',   test_cb2, (void*)"Submenu1", FL_SUBMENU},
       {"A very long menu item"},
       {"&submenu",FL_CTRL+'S',  0, (void*)"submenu2", FL_SUBMENU},
         {"item 1"},
```

Feel free to defer this until after 1.4.0, if the implications of this change need to be ironed out first. But since this change isn't backwards compatible, strictly speaking, it would be useful to have this change in 1.4.0 rather than 1.4.x.
I think the "risk" for existing 1.3-based applications is very small, but not non-existent.

### CODE REVIEW

**Comment by Albrecht-S** [comment]
Thanks for this PR, it's very much appreciated. However, I'm not the person to look into this, other FLTK devs know more about menu handling.

> Feel free to defer this until after 1.4.0, if the implications of this change need to be ironed out first. But since this change isn't backwards compatible, strictly speaking, it would be useful to have this change in 1.4.0 rather than 1.4.x.

Actually I thought more about 1.5.0 rather than 1.4.x (x > 0) for this PR that changes behavior of the UI. Our goal with 1.4.x is to stay as close as possible to 1.3.x, and this includes behavioral changes of the UI. But that's only my thought (w/o testing), others may find this change tolerable...

**Comment by MatthiasWM** [comment]
I like the change in behavior for the menu. It makes a lot of sense and duplicates the behavior of macOS menus. For example, pressing enter on a submenu item now opens the submenu instead of dismissing the entire menu. Makes sense to me. Esc for dismissing the menu still works.

I would apply the patch.

**Comment by Albrecht-S** [comment]
> I would apply the patch.

@MatthiasWM IMHO you are the one who knows menu code and behavior best, hence I'd say if you think it's good to go, please feel free to merge it. I wouldn't mind...

**Comment by MatthiasWM** [comment]
Verified. Seems to be working nicely.

**Pull request merged**
