### PR TITLE
New PR for PR #99: Branch issue-99 rebased and edited

### PR DESCRIPTION
**Pull request by Albrecht-S**
The new branch `issue-99a` is based on Greg's branch `issue-99`.

I squashed some commits (integrated fixups) but left the main commits alone. I also added `setlocale()` to `fluid` since this is also used in the native (GTK) filechooser widget (tested on Linux).

To apply this branch to the main FLTK repo I suggest to **merge** it, i.e. keep the history of branch `issue-99a`.

For further information please visit #99 "Add error message box to Fl_File_Chooser (STR 1086)" and [STR 1086](https://www.fltk.org/str.php?L1086) which should both be closed when done.

### CODE REVIEW

**Comment by Albrecht-S** [comment]
@erco77 Hi Greg, I added this PR after I decided to edit the existing commits of branch `issue-99` and pushed a new branch `issue-99a` so we have a formal PR that can be applied cleanly. It's a demo and exercise - actually it wouldn't have been necessary, but I like it.

It's also a learning process (for me, you, and hopefully for the team). In cases like this where we have a substantial amount of commit messages with valuable comments and several step-by-step commits I suggest to **merge** this branch eventually (soon!) to keep the remaining history of branch issue-99a.

Please review. If you agree that we're done (and to merge as opposed to squash and rebase), I'd like to go ahead and merge this new branch. Finally we can delete the old branch issue-99.

**Comment by erco77** [comment]
Ah, good catch on setlocale() with fluid.

OK, so just for my understanding:

- This is a new PR to rellace of #99 (which was associated with your fork).
- This is a new PR #103, and it's for the new branch, issue-99a in the FLTK master, no longer associated with your original fork

If I understand that correctly, sounds good/clean to me.

You want me to merge, OK, I'll see about doing that now after I look over the new difs.

**Comment by erco77** [comment]
OK, merged, no conflicts.

Should we delete all the issue 99 branches before closing? I think there's three right now.

**Comment by Albrecht-S** [comment]
GitHub says it all (above the comment entry box): "Pull request successfully merged and closed. You’re all set—the `issue-99a` branch can be safely deleted." And there's also a button "Delete branch" next to the text to do this with one click. This will, of course, delete only the branch of this PR, i.e. `issue-99a`. I'm leaving this to you so you can try it yourself.

Meanwhile I deleted the other two working branches which closed PR #99 automatically.
I also closed STR 1086.

**Comment by Albrecht-S** [comment]
Hint: Once the branches are deleted in the remote repository (`origin`) the only thing you need to do in your local working copy is:
```
$ git remote prune origin
Pruning origin
URL: git@github.com:fltk/fltk.git
 * [pruned] origin/issue-99
 * [pruned] origin/issue_99
```
As you see, this deletes the local branches from your local repository that no longer exist in the remote repository.
In my case I also pruned the deleted branch from my fork:
```
$ git remote prune albrecht
Pruning albrecht
URL: git@github.com:Albrecht-S/fltk.git
 * [pruned] albrecht/str-1086_file-chooser
```

**Comment by Albrecht-S** [comment]
@erco77
> Should we delete all the issue 99 branches before closing? I think there's three right now.

As noted elsewhere I deleted two of them, leaving `issue-99a` for you to delete with the "Delete branch" button. And this PR is already closed, but it's called _"Merged"_ in the case of PR's.

**Pull request merged**
