### PR TITLE
New Fl_ICO_Image class to read Windows .ico icon files

### PR DESCRIPTION
**Pull request by ManoloFLTK**
Many thanks to @darealshinji for contributing all the code for this new FLTK class.
This is essentially the code from branch Fl_ICO_Image of https://github.com/darealshinji/fltk updated to today's FLTK source code and documented.

### CODE REVIEW

**Comment by Albrecht-S** [comment]
@ManoloFLTK Code looks good, I added a missing 'const' qualifier and fixed trailing whitespace in commit 6639f9b982c1f2014a2cfeeae5be6b485fbd6181.

Note that I didn't test anything, but feel free to rebase/squash/merge if you tested loading ICO images with the new code (which I assume, of course). Thanks for taking and finishing @darealshinji's PR #54.

**Review by Albrecht-S — APPROVED** [review]
Good to go but not tested by me.

**Comment by Albrecht-S** [comment]
... and please don't forget to close #54 when done.

**Comment by Albrecht-S** [comment]
@ManoloFLTK You force-pushed your branch - presumably using your local version - and thus removed my commit. Was this by accident or intentionally?

Anyway, applying and **pushing** my patch again **to your fork**.
Commit 0bb30d8f92839af826fb389fccd625c74e981a13 pushed.

**Comment by ManoloFLTK** [comment]
> @ManoloFLTK You force-pushed your branch - presumably using your local version - and thus removed my commit. Was this by accident or intentionally?

This was by accident. My intention was to rebase the ICO_Image branch with its 2 commits (mine and yours). Apparently that's not what git understoood. I was preparing to replicate your commit. Thanks for having done it before.

Who has rights to push to my branch?

**Comment by Albrecht-S** [comment]
> Who has rights to push to my fork?

I think it is:
1. users with write access **or** (only) maintainers of the main (fltk/fltk) repository
2. but only to the branch of a given PR
3. and only if the owner of the PR allowed it.

The latter (3.) is the default, i.e. users who create a PR allow maintainers (see 1.) to push to their branches in their forks. A user who creates a PR **can** disable this but the default is there for a reason: it is intended for those working on a user's PR to modify or even rebase/force-push it before merging.

You can see if **you** are allowed to push to someone else's branch/fork if you see a GitHub message like "Add more commits by pushing to the `branch-name` branch on `user's fork name`".

If you have further questions regarding this please send me a private mail.

**Pull request merged**
