### PR TITLE
add resize documentation as per STR3433

### PR DESCRIPTION
**Pull request by engelsman**
add resize chapter to documentation, plus images,
based on Article #415: How does resizing work?
https://www.fltk.org/articles.php?L415

see also https://www.fltk.org/str.php?L3433

### CODE REVIEW

**Comment by erco77** [comment]
Great!
I noticed the file sizes seemed large for the image content; I found I could shrink the image's data sioze from 19k to just 3k in GIMP by just converting the image to use a 16 color map, without much of any change in image quality:
Original (19k): http://seriss.com/people/erco/tmp/a.png
Colormap (2k): http://seriss.com/people/erco/tmp/aa.png
If you want I can provide the steps in gimp, or I can convert them.. if the latter is preferred, hmm, what's the best way for me to provide them using git?

**Comment by Albrecht-S** [comment]
Thanks @engelsman.

@erco See the GitHub note below the last comment (above the "checks"):

> Add more commits by pushing to the str3433-resize-dox branch on engelsman/fltk.

This indicates that we are **allowed** to push commits to @engelsman's repository (which is an option when you create a PR).

I didn't try this in practice yet, but if you agree with @engelsman that you convert the images, then you should be able to replace them in a commit and push that commit to @engelsman's repo.

**Comment by Albrecht-S** [comment]
Well, now I did it. I fixed some typos and trailing whitespace in one commit and pushed to @engelsman's repo/PR (branch str3433-resize-dox). Worked well.

@engelsman I hope you don't mind. As you know we're learning issue and PR handling, and this was an opportunity I could not resist.

I built the docs and my comment is: **awesome** ! Looks great, images are great, explanation is well done (I know you copied most parts from the article, but still: well done). Thanks.

**Comment by erco77** [comment]
OK, I was able to shrink all the pngs down to smaller than 10k each, committed to the branch as 25dd627,
details in the commit.

**Comment by engelsman** [comment]
@erco77 : Thanks for shrinking the images: I was worried they were much bigger than the others.

@Albrecht-S : what happens now? Do I have to pull my str3433-resize-dox branch to see/check changes?

As I said in the STR itself, if everyone is happy that this section fits between common widgets and the editor chapters, then all of the chapter relative numbering needs to be updated in this and the following chapters. Do you want me to continue committing these changes on the str3433-resize-dox branch before the PR can be closed?

I've only tested "make html" on MacOS 10.15.5 and with doxygen 1.8.17, which gives warnings about deprecated PERL_PATH and MSCGEN_PATH, but I didn't want to change them if they are still "expected" in older versions.

Once we're all sorted here, I will create another pull request with str3433-resize-examples containing the programs that I used to create the images. These are compliant to the new headers and layout, but the variable naming is a bit quick and dirty. But let's cross that bridge when we get there.

**Comment by Albrecht-S** [comment]
@engelsman wrote
> what happens now? Do I have to pull my str3433-resize-dox branch to see/check changes?

Sure, just use
```
git checkout str3433-resize-dox # if you're not on this branch
git pull
```
The latter would pull our commits into your local repository. Just in case you did already commit (but not yet pu[bli]sh), you should use `git pull --rebase` instead which would avoid unwanted merge commits. There's no need to change the PR, it records all the commits.

Once we're all done we can either _merge_ (keeping the branch commits separate and add one merge commit), _squash and merge_, or _rebase and merge_ which would handle the commits differently.

In this case I'd prefer to squash because this would entirely eliminate the larger images and keep only the small ones reducing size of the fltk/fltk repo which has to be downloaded by every user.

There's another thing you can do in your local repo: `git rebase -i' would allow you to squash all commits to one, but I don't know how GitHub would handle this. Then you'd have to either force-push `git push -f origin str3433-resize-dox` your changes (this might break the PR, I don't know) or push your changes to another branch and create a new PR. I'd like to **try** the former (`rebase -i` and `push -f`) because I'd like to see how GitHub would deal with this. Feel free to decide, it's all experimental.

In all cases the worst thing that could happen would be that we'd need to create a new PR.

**Comment by engelsman** [comment]
Sorry, I was a bit too impatient... and it's all under git if I screw up, no? ...
I already pulled your typo fixes and Greg's image resizes, and have made
a new commit about figure renumbering and Prev/Next page links and
pushed the whole lot back again.

I now have a new backup branch, so will try to squash and merge the pull request branch.
I'll need to look up the exact commands requested first.
This rebasing stuff is all new to me :-)

**Comment by Albrecht-S** [comment]
@engelsman WRT chapter and figure numbers: +1, thanks.

Impatience? Nope, don't worry. I was too late to the party. And yes, git is great.

Regarding your doxygen question: no warnings here with 1.8.13, but this is a common issue. I always left the old code for users of older versions - unless it is _clear_ that we were using only the _defaults_; then I removed the old definitions to avoid deprecation warnings. But this should be done in separate commits anyway (maybe another issue or PR).

I also created the PDF and it looks fine. Lots of white space though, but I didn't compare with other chapters, maybe this is normal.

**Comment by engelsman** [comment]
OK, I've just tried a "git rebase -i master testing" and then changed the commands to:

```
pick 5a2469685 add resize documentation as per STR3433
fixup a8e4f62b0 Fix typos and trailing whitespace
fixup 25dd627e9 Decreased pngs to all less than 10k using GIMP
fixup 0db2df825 fix Figure numbers and Prev/Next links in dox

X Rebase 2984fe638..0db2df825 onto 0db2df825 (4 commands)
```

and it appears to work for the testing branch, will try on str3433-resize-dox and try an ordinary push... BRB

**Comment by engelsman** [comment]
```
duncan$ git push origin str3433-resize-dox
To https://github.com/engelsman/fltk.git
 ! [rejected]            str3433-resize-dox -> str3433-resize-dox (non-fast-forward)
error: failed to push some refs to 'https://github.com/engelsman/fltk.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

will now try the "git push -f origin str3433-resize-dox" ... BRB

**Comment by engelsman** [comment]
Just checking that the failed push didn't leave some fallout...
```
duncan$ git status
On branch str3433-resize-dox
nothing to commit, working tree clean
```

No, it all looks good, so let's try forcing it...
```
duncan$ git push -f origin str3433-resize-dox
Enumerating objects: 33, done.
Counting objects: 100% (33/33), done.
Delta compression using up to 4 threads
Compressing objects: 100% (21/21), done.
Writing objects: 100% (21/21), 46.37 KiB | 15.46 MiB/s, done.
Total 21 (delta 12), reused 0 (delta 0)
remote: Resolving deltas: 100% (12/12), completed with 12 local objects.
To https://github.com/engelsman/fltk.git
 + 0db2df825...97ec249c0 str3433-resize-dox -> str3433-resize-dox (forced update)
duncan$
```

Well it all seems to have worked, but now I don't see the additional 3 commits on my github page, which is to be expected, but there are still links in your comments to the "missing" commits. I presume that these still appear somewhere within *my* fork, and that the large image files won't get copied into the fltk repo. How to check?

**Comment by Albrecht-S** [comment]
Great, thanks for testing. Now we know that GitHub can cope with force-pushing a PR's branch. GitHub "says":
```
engelsman wants to merge 1 commit into fltk:master from engelsman:str3433-resize-dox
```

whereas it said "3 commits" or such before.

That's good to know (for my documentation).

**Comment by Albrecht-S** [comment]
> … there are still links in your comments to the "missing" commits. I presume that these still appear somewhere within my fork, and that the large image files won't get copied into the fltk repo. How to check?

Well, hard to say if you're really paranoid ;-)

Good evidence is `git whatchanged master..<branchname>`. Do you see the files? You should only see the images once. You can fetch and store the image from Git and view it. I'll show this in my next reply, for a good reason.

And yes, the big images are still in your repository. Git keeps everything for some time and does its own garbage collection. Generally spoken Git keeps everything that is "reachable" from any known commit, tree, or other reference. A key point is `git reflog` which shows you the Git refs you've visited in the past. You'll find your previous branch (before the rebase) there. Hence everything is still there and you can recover everything you need: just set a `git tag` or create a new branch on the Git hash you find in `git reflog`, and you got everything back. BTW, `gitk` is a valuable tool, particularly but not only for "beginners". It shows history with diffs and can be very helpful if you are confused about the status of your repository. I'm very often using it and learning more and more about it, for instance that you can delete obsolete branches with its GUI.

BTW, you can force garbage collection with `git gc` but this is OT for now.

Another way to find out if the images are still there is to clone your repository to another folder. You can try to find the old images if you know there SHA1 value. See my next reply for more.

**Comment by Albrecht-S** [comment]
OK, now you force-pushed your branch. How do we (coworkers) recover from this? I'll tell you with a log of my activities:
```
(on branch str3433-resize-dox)
$ git fetch
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 21 (delta 12), reused 21 (delta 12), pack-reused 0
Unpacking objects: 100% (21/21), done.
From github.com:engelsman/fltk
 + 0db2df825...97ec249c0 str3433-resize-dox -> engelsman/str3433-resize-dox  (forced update)
   2b88ce521..2984fe638  master             -> engelsman/master
```

OK, we see that it's a _"forced update"_.
```
$ git status
On branch str3433-resize-dox
Your branch and 'engelsman/str3433-resize-dox' have diverged,
and have 4 and 3 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```

Git is not very helpful in this situation, it tells us that we shall "git pull to merge...", but this would create merges and we'd still have all commits (and the big images) in our repo. That's not what we want here.

But Git also says: "On branch str3433-resize-dox" and "nothing to commit, working tree clean". Great! Now we can reset our local branch to the tip of your (remote) branch and we're done:
```
$ git reset --hard engelsman/str3433-resize-dox
HEAD is now at 97ec249c0 add resize documentation as per STR3433
```

Note: use `git reset --hard` with care. This is one of the Git commands that is **NOT revertible !!!** It _**will reset your working copy and all files you might have edited**_. That's why I mentioned that Git said "working tree clean". You have been warned!

Another option would have been to delete our local branch and recreate it from the remote branch. But `git reset` is faster. Use whatever you like.

Next step: verify the correct status:
```
$ git whatchanged master..str3433-resize-dox
commit 97ec249c011854de707a3e81b979209fc651d190 (HEAD -> str3433-resize-dox, engelsman/str3433-resize-dox)
Author: Duncan Gibson <engelsman@users.noreply.github.com>
Date:   Sat Jul 11 01:03:09 2020 +0200

    add resize documentation as per STR3433
    
    add resize chapter to documentation, plus images,
    based on Article #415: How does resizing work?
    https://www.fltk.org/articles.php?L415
    
    see also https://www.fltk.org/str.php?L3433

:100644 100644 f619a7fa1 893f3bd28 M	documentation/Doxyfile.in
:100644 100644 0c03b8c56 a1c370799 M	documentation/Makefile
:100644 100644 2c586a352 4f7a59011 M	documentation/src/common.dox
:100644 100644 4e12affb2 3ec17d6c0 M	documentation/src/drawing.dox
:100644 100644 77c8bbaa5 91123fc2c M	documentation/src/editor.dox
:100644 100644 4bd3ccd0d 85dd74d76 M	documentation/src/examples.dox
:100644 100644 b42aafeb7 766fe5252 M	documentation/src/faq.dox
:100644 100644 9d1e1fcc4 25bc56c65 M	documentation/src/fluid.dox
:100644 100644 09b4545bd 6dafc22de M	documentation/src/index.dox
:000000 100644 000000000 6b85245dc A	documentation/src/resize-example1.png
:000000 100644 000000000 33d3040b2 A	documentation/src/resize-example2.png
:000000 100644 000000000 b20ba3c85 A	documentation/src/resize-example3a.png
:000000 100644 000000000 b2ed1475c A	documentation/src/resize-example3b.png
:000000 100644 000000000 ac8c4d640 A	documentation/src/resize-example3c.png
:000000 100644 000000000 5a1d6b92d A	documentation/src/resize-example4a.png
:000000 100644 000000000 4ab748f8c A	documentation/src/resize-example4b.png
:000000 100644 000000000 84698d3df A	documentation/src/resize.dox
```

You see only one commit and all changed files with their previous and new SHA1 values (000000000 for new/created files).

Now to the verification of the image files: we see each image file appeared once and was created from NULL. How can we see the file? Git has some "plumbing commands" that don't show up in the user help info. You need to look them up in the docs, I'm not going into details here.

One of the standard user commands is `git show` and it can be used with a SHA1 to get info about and retrieve any object from the repository. You can use it like this:
```
$ git show 6b85245dc > temp.png
$ ls -l temp.png
-rw-r--r-- 1 xxx xxx 9422 Jul 11 16:24 temp.png
```

Obviously `resize-example3b.png` (6b85245dc) is 9422 bytes long. Use your favorite image viewer to see it.

Exercise: Try this in a clean checkout with the `SHA1` of one of the older, larger images. ;-)

Last but not least: a `git reflog` example:
```
$ git reflog
97ec249c0 (HEAD -> str3433-resize-dox, engelsman/str3433-resize-dox) HEAD@{0}: reset: moving to engelsman/str3433-resize-dox
0db2df825 HEAD@{1}: pull: Fast-forward
a8e4f62b0 HEAD@{2}: reset: moving to HEAD
$ git log master..a8e4f62b0
commit a8e4f62b032693dadd4a5e32bce737c8ed7c9374
Author: Albrecht Schlosser <albrechts.fltk@online.de>
Date:   Sat Jul 11 04:52:13 2020 +0200

    Fix typos and trailing whitespace

commit 5a24696855578325b38dfdeba175f7570c79677e
Author: Duncan Gibson <engelsman@users.noreply.github.com>
Date:   Sat Jul 11 01:03:09 2020 +0200

    add resize documentation as per STR3433
    
    add resize chapter to documentation, plus images,
    based on Article #415: How does resizing work?
    https://www.fltk.org/articles.php?L415
    
    see also https://www.fltk.org/str.php?L3433
```

As you can see I had not been up-to-date with my local branch (at a8e4f62b0) as `git log master..a8e4f62b0` shows.

Exercise 2: Use these SHA1's (or your own `git reflog`) to find the SHA1's of the old images and extract one of these to show they're still there. Try this in your "other" fresh checkout.

I hope this is helpful and if not for anybody else, then for the Git documentation I intend to write...

**Comment by engelsman** [comment]
In one of my intermediate versions, where the text now says "if the \p resizable is set to zero" for example, I did have the inline code snippet "if <tt>group->resizable() == 0</tt>" but I found that it got a bit clunky so I simplified it.

What might work instead without re-writing the text itself would be to have a summary "code" block at the top of the three sections (or after the first paragraph if that looks better) such as:

```
  Summary:
    group->resizable(0);
    if (group->resizable() == 0) { . . . }
```

```
  Summary:
    group->resizable(group);
    if (group->resizable() == group) { . . . }
```

```
  Summary:
    group->resizable(child);
    if (group->resizable() == child) { . . . }
```

Or something like that. I'm in the middle of something else, and will be going out shortly, so can't check the different layout options myself.

**Comment by engelsman** [comment]
Or maybe those summaries should be more complete pseudocode examples:

```
  Summary:
    group = new Fl_Group(xg, yg, wg, hc, "No Resizing");
    child1 = new FL_Box(xg+xb, yg+yb, wb, hb, "B");
    . . .
    group->resizable(0); // no resizing
    group->end();
```

```
  Summary:
    group = new Fl_Group(xg, yg, wg, hc, "Simple proportional resizing");
    child1 = new FL_Box(xg+xb, yg+yb, wb, hb, "B");
    . . .
    group->resizable(group); // simple proportional resizing
    group->end();
```

```
  Summary:
    group = new Fl_Group(xg, yg, wg, hc, "Complex resizing");
    child1 = new FL_Box(xg+xb, yg+yb, wb, hb, "B");
    . . .
    group->resizable(child1); // complex resizing
    group->end();
```

**Comment by Albrecht-S** [comment]
@erco77 Good catch.
@engelsman Code examples are always helpful (we do already have one).

Here's another suggestion how it could be done:

> The resizing is implemented within the Fl_Group widget, and the exact resizing behavior of that group is determined by its \link Fl_Group::resizable() resizable() \endlink attribute.

See [Doxygen docs](https://www.doxygen.nl/manual/commands.html#cmdlink).

Looks good to me in the generated HTML docs. I think it would be sufficient to add this link once in the description and use plain text later on.

Just my 2 ct.

**Comment by engelsman** [comment]
Oops! Add additional comment to summary:

```
  Summary:
    group = new Fl_Group(xg, yg, wg, hc, "No Resizing");
    child1 = new FL_Box(xg+xb, yg+yb, wb, hb, "B"); // or other widget type
    . . .
    group->resizable(0); // no resizing
    group->end();
```

**Comment by Albrecht-S** [comment]
My example would look like this:

"The resizing is implemented within the [Fl_Group](https://fltk.gitlab.io/fltk/classFl__Group.html) widget, and the exact resizing behavior of that group is determined by its [resizable()](https://fltk.gitlab.io/fltk/classFl__Group.html#ab0ed0d1974d7185594687849f386c5f3) attribute."

**Comment by engelsman** [comment]
Yes, we can also have a doxygen link to FL_Group::resizable() in the header paragraph. I forgot about that option.

Note that the Fl_Group doxygen comments need a bit of a tweak themselves, because resizable() says:
See void Fl_Group::resizable(Fl_Widget *box)
which links to a description that doesn't really explain clearly why you would use a box.

**Comment by erco77** [comment]
More indepth (multiline) example source later in the text is always good. In the intro lines, I figured just naming the method was all that was needed, knowing it would then be expanded on later in the text.

Gonna wait until this morning coffee gets into my bloodstream to where I can do a proof read..!

**Comment by engelsman** [comment]
@Albrecht-S @erco77 I pushed a commit to my fork with the resizable() link in the first paragraph, and the summary code examples, and I can see the change when I compare my branch, but it doesn't show up in this pull request.

I was about to rebase the str3433-resize-dox branch with upstream on my local repo to squash it down to one commit again when github went offline for a while. Should I still do that, and force push it, or am I too late because the Approval process has started?

**Comment by Albrecht-S** [comment]
@engelsman I have no idea what caused the missing commit in this PR. I dismissed my review now to see if it changes anything, but it didn't (until now). Would be interesting what happens if you add and push another commit (just for testing purposes) or if one of us did this.

Another option would indeed be to rebase the branch as-is, just using `git rebase [upstream/]master` (after updating [upstream/]master) and to force-push, as you wrote. Yes, I'd like you to try this. Canyou please do this?

OT: I've also recently seen that one commit that built successfully on Travis-CI is still in a "queued" state although Travis-CI shows success. Maybe it's something with GitHub's communication that's out of sync. Unfortunately I don't know how to "fix" it (other than trying another commit or push).

**Comment by engelsman** [comment]
I fetched and merged upstream with my master this morning, before the github hiatus (and there haven't been any commits on master since then, as far as I can see) so am about to "git rebase -i master str3433-resize-dox" with the following:

```
pick 97ec249c0 add resize documentation as per STR3433
fixup 4d531b0a4 add resizable() link and example code to resize.dox
X Rebase 9925b0f12..4d531b0a4 onto 9925b0f12 (2 commands)
```

which worked, so I shall now "git push -f origin str3433-resize-dox"
and that looks like it worked

**Comment by erco77** [comment]
I've only done one push for the image size change AFAIK.
My only other involvement would be my additions to the review.
I imagine github might keep a record of all activity to the repo to see what happened..?

**Pull request merged**
