### PR TITLE
Fix inconsistencies with Tab/Backspace handling in menus

### LINKED ISSUE #1156: Menubars: Tab wraps but Shift+Tab / Backspace do not
**Describe the bug**

TL;DR: In menubars, Shift+Tab and Backspace behave inconsistently with Tab in 3 different ways.

From https://github.com/fltk/fltk/issues/1155#issuecomment-2526191563

1. In 1.4.0, using Tab to move down a submenu wraps back to the start, but Shift+Tab and Backspace do not wrap. (It might be worth noting that the up/down arrow keys do not wrap either, and this is probably intentional. Only left/right arrow keys wrap for topmenu items. I'm not suggesting any changes to arrow key handling, just drawing comparisons.)

2. Also, if Shift+Tab or Backspace is held so that the selection moves back to the start, then right (for topmenus) or down (for submenus) needs to be pressed twice in order to move the selection once.
(This is probably a mostly unimportant detail, because if the wrapping is fixed then this bug would probably go away. But just mentioning for completeness.)

3. If a topmenu item is currently highlighted, then Tab will move down and enter the first submenu item (it does _not_ move right to the next topmenu item). But Shift+Tab moves left to the previous topmenu item (whereas I would expect it to move to the last/bottom submenu item (like the actual opposite of Tab)).

**To Reproduce**

Bugs 1 and 2:

1. Run test/menubar
2. Click on a menu item in the middle, like Font
3. Press Tab
4. See that the selection moves down into the submenu
5. Hold Tab
6. See that the selection wraps within that submenu
7. Hold Shift+Tab or Backspace
8. Bug 1: See that the selection does not wrap (stops at the top of the submenu)
9. Bug 2: Notice that you must press down TWICE to move the selection

Bug 3:

1. Run test/menubar
2. Click on a menu item in the middle, like Font
3. Press Shift+Tab or Backspace
4. Bug 3: See that the selection moves left to Radio instead of the bottom of the Font submenu (the arrow symbol menu item below Shadow)
5. From here, pressing Tab goes down into the Radio submenu (which is expected, just pointing out the contrast with the Shift+Tab press from steps 3/4)

**Expected behavior**

Shift+Tab and Backspace should probably wrap like Tab.
Shift+Tab and Backspace should probably stick to submenus like Tab.

**Screenshots**

Screenshots/videos are probably more confusing than helpful in this case because you can't see what my keyboard is doing so it's unclear when I'm using tab/backspace/arrow keys.

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 5ff42dd

**FLTK Configure / Build Options**
 - Default CMake build

**Operating System / Platform:**
 - OS: Multiple
 
 **Additional context**

Bugs 1 and 2 can also be seen with any of the choice dropdowns in test/menubar.
Bug 3 is unique to top level menubars.

### LINKED ISSUE #1158: Hang/Infinite loop on submenu with all inactive/invisible items
**Describe the bug**

If a menubar contains only inactive and invisible items, and the mouse is pressed on the menubar and then the left or right arrow key is pressed, FLTK gets stuck in an infinite loop in `forward()` or `backward()`.

**To Reproduce**

Apply this patch to test/menubar.cxx to make all the top-level items inactive or invisible:

```diff
diff --git a/test/menubar.cxx b/test/menubar.cxx
index a5ccfc234..1c0f5a898 100644
--- a/test/menubar.cxx
+++ b/test/menubar.cxx
@@ -67,7 +67,7 @@ Fl_Menu_Item hugemenu[100];
 
 Fl_Menu_Item menutable[] = {
   {"foo",0,0,0,FL_MENU_INACTIVE},
-  {"&File",0,0,0,FL_SUBMENU},
+  {"&File",0,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {"&Open",   FL_ALT+'o', 0, 0, FL_MENU_INACTIVE},
     {"&Close",  0,      0},
     {"&Quit",   FL_ALT+'q', quit_cb, 0, FL_MENU_DIVIDER},
@@ -108,7 +108,7 @@ Fl_Menu_Item menutable[] = {
       {"after submenu"},
       {0},
     {0},
-  {"&Edit",FL_F+2,0,0,FL_SUBMENU},
+  {"&Edit",FL_F+2,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {"Undo",        FL_ALT+'z',  0},
     {"Redo",        FL_ALT+'r',  0, 0, FL_MENU_DIVIDER},
     {"Cut",         FL_ALT+'x',  0},
@@ -120,7 +120,7 @@ Fl_Menu_Item menutable[] = {
     {"Preferences", 0,           0},
     {"Size",        0,           0},
     {0},
-  {"&Checkbox",FL_F+3,0,0,FL_SUBMENU},
+  {"&Checkbox",FL_F+3,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {"&Alpha",  FL_F+2, 0, (void *)1, FL_MENU_TOGGLE},
     {"&Beta",   0,      0, (void *)2, FL_MENU_TOGGLE},
     {"&Gamma",  0,      0, (void *)3, FL_MENU_TOGGLE},
@@ -133,7 +133,7 @@ Fl_Menu_Item menutable[] = {
     {"00",      0,      0, (void *)1, FL_MENU_TOGGLE},
     {"000",     0,      0, (void *)1, FL_MENU_TOGGLE},
     {0},
-  {"&Radio",0,0,0,FL_SUBMENU},
+  {"&Radio",0,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {"&Alpha",  0,      0, (void *)1, FL_MENU_RADIO},
     {"&Beta",   0,      0, (void *)2, FL_MENU_RADIO},
     {"&Gamma",  0,      0, (void *)3, FL_MENU_RADIO},
@@ -146,7 +146,7 @@ Fl_Menu_Item menutable[] = {
     {"00",      0,      0, (void *)1, FL_MENU_RADIO},
     {"000",     0,      0, (void *)1, FL_MENU_RADIO},
     {0},
-  {"&Font",0,0,0,FL_SUBMENU /*, 0, FL_BOLD, 20*/},
+  {"&Font",0,0,0,FL_SUBMENU|FL_MENU_INACTIVE /*, 0, FL_BOLD, 20*/},
     {"Normal",  0, 0, 0, 0, 0, 0, 14},
     {"Bold",    0, 0, 0, 0, 0, FL_BOLD, 14},
     {"Italic",  0, 0, 0, 0, 0, FL_ITALIC, 14},
@@ -157,7 +157,7 @@ Fl_Menu_Item menutable[] = {
     {"Shadow",  0, 0, 0, 0, (uchar)FL_SHADOW_LABEL},
     {"@->",     0, 0, 0, 0, (uchar)FL_SYMBOL_LABEL},
     {0},
-  {"&International",0,0,0,FL_SUBMENU},
+  {"&International",0,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {"Sharp Ess",0x0000df},
     {"A Umlaut",0x0000c4},
     {"a Umlaut",0x0000e4},
@@ -169,7 +169,7 @@ Fl_Menu_Item menutable[] = {
     {"Hangul character Sios &\xe3\x85\x85"},
     {"Hangul character Cieuc", 0x003148},
     {0},
-  {"E&mpty",0,0,0,FL_SUBMENU},
+  {"E&mpty",0,0,0,FL_SUBMENU|FL_MENU_INACTIVE},
     {0},
   {"&Inactive", 0,      0, 0, FL_MENU_INACTIVE|FL_SUBMENU},
     {"A very long menu item"},
@@ -179,8 +179,8 @@ Fl_Menu_Item menutable[] = {
     {"A very long menu item"},
     {"A very long menu item"},
     {0},
-  {"&Huge", 0, 0, (void*)hugemenu, FL_SUBMENU_POINTER},
-  {"button",FL_F+4, 0, 0, FL_MENU_TOGGLE},
+  {"&Huge", 0, 0, (void*)hugemenu, FL_SUBMENU_POINTER|FL_MENU_INACTIVE},
+  {"button",FL_F+4, 0, 0, FL_MENU_TOGGLE|FL_MENU_INACTIVE},
   {0}
 };
```

1. Apply the above patch and run test/menubar
2. Click on the menubar
3. Press Left or Right
4. See that FLTK has hung

**Expected behavior**

Nothing should happen when left or right is pressed on a menubar of inactive items.

Arguably, a menubar with all inactive/invisible items shouldn't even take focus when pressed with the mouse. But that can be left alone for now.

**Video**

https://github.com/user-attachments/assets/fedcbfa6-355b-4b25-b554-e28881f85ffd

**FLTK Version**
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 5ff42dd

**FLTK Configure / Build Options**
 - Default CMake options

**Operating System / Platform:**
 - OS: Windows
 - OS Version: Windows 11

**Additional context**

I'll include a simple fix with #1157.

### PR DESCRIPTION
**Pull request by dannye**
Fixes #1156 and Fixes #1158

### CODE REVIEW

**Comment by dannye** [comment]
I'm done making changes. This fixes some minor bugs (#1156) and a serious, albeit rare, bug (#1158).
@MatthiasWM I would appreciate your review. I've verified on Windows so far, but I'll test on Mac and Linux quickly.

**Comment by MatthiasWM** [comment]
@dannye thanks for the fixes. I will look at it tomorrow, latest Tuesday.

**Comment by dannye** [comment]
Conflicts resolved.

**Comment by ManoloFLTK** [comment]
@dannye: please consolidate all proposed changes in a single commit relative to the head of the git FLTK repository.

**Comment by dannye** [comment]
In this case, having the individual commits makes it easier to review the individual ideas. Especially because of the extended commit messages on each individual change that explain the rationale.

"Squash and merge" will consolidate all changes into a single commit and give the person who clicks merge an opportunity to tidy up the final commit message. (By default, "Squash and merge" will pre-populate with a list of all individual commit messages, but meaningless ones can be pruned before merging (like my "formatting" commit message for example) if so desired.)

If you feel strongly, I will squash and rebase my source branch, but I don't think it's necessary.

**Comment by MatthiasWM** [comment]
Reviewing now...

**Comment by Albrecht-S** [comment]
> If you feel strongly, I will squash and rebase my source branch, but I don't think it's necessary.

@dannye and FLTK devs: I agree that it's sometimes useful to have separate commits and eventually merge them individually. But this is probably only necessary if - more or less - unrelated things are committed in one PR (which should be avoided). I remember a case where a user contributed a PR that was incomplete (but not wrong) and I added another commit and kept both commits separate for clear documentation.

OTOH, when one created more than one commit because of corrections and amendments, then it's good style (as a contributor or FLTK dev) to squash and potentially rebase these commits even before the merge is attempted. Note that we prefer rebasing rather than merging the master branch "downstream" into the PR's branch. This makes it easier to review the changes.

And, that all said, yes, GitHub has different merge modes that can be used sensibly.

@dannye Thanks for all your continued work on FLTK, it's very much appreciated.

**Comment by MatthiasWM** [comment]
I believe I checked all paths, and it seems fine to me. I do not use keyboard navigation much, so I have no comparison between a before and after.

**Review by MatthiasWM — COMMENTED** [review]
Ok.

**Pull request merged**
