### PR TITLE
Shared and static libraries side-by-side

### PR DESCRIPTION
**Pull request by dvzrv**
Changing configuration to be able to build static and shared libraries side-by-side (libfltk.{a,so}).

This looks a little ugly, but is at least descriptive without changing too much code.
I had to forward-port my patch for 1.3.5 for current master and hope I didn't miss anything.

Another thing to do after this is to fix the output of fltk-config to be able to specifically return shared or static libraries (e.g. `fltk-config --libs` returns shared lib instead of static lib and/or introducing a new flag, that returns it).

Implements #20

### CODE REVIEW

**Comment by dvzrv** [comment]
Also, there's tab poisoning! :)

**Comment by Albrecht-S** [comment]
Thanks for your PR. I see what you did but I can't tell if this is all correct yet, I didn't find the time to look into the details because I'm pretty busy with another project.

WRT "tab poisoning": I don't understand what exactly you mean here. We **allow** tabs but require tab settings of 8 columns. Using only spaces is also fine, even mixing tabs and spaces in one file is common and accepted.

In our code we're indenting with 2 spaces, but unfortunately the CMake code doesn't strictly adhere to it. You should perhaps do your edits in a similar way as in the surrounding code.

Thanks for your contribution, I'll take a closer look when time permits. Thanks also for fixing the broken build in your second commit!

**Comment by Albrecht-S** [comment]
One other note, regarding fltk-config: fltk-config already has different commandline arguments for static and shared libs. See `fltk-config --help`:

    [--ldflags]       return flags to link against FLTK
    [--ldstaticflags] return flags to link against static FLTK library even if there are DSOs installed
    [--libs]          return FLTK libraries full path for dependencies

I'm not sure about the necessary changes (yet).

**Comment by dvzrv** [comment]
`fltk-config --libs` returns `/usr/lib64/libfltk.a` for me.
I think it should be 
`fltk-config --libs` -> `/usr/lib64/libfltk.so`
`fltk-config --staticlibs` -> `/usr/lib64/libfltk.a`

But that's for another pull request!

**Comment by KBentley57** [comment]
All,

I'd like to request that this be pulled in for the 1.3.6 (?) branch, or later.  I came up on this issue today, where FLTK builds the shared libraries, but the FindFLTK.cmake provided by cmake3 on centos 7.5 only looks for the static libs.  As a workaround, I've make sym links from the libfltk*_SHARED.so to libfltk*.so.

Thanks,

Kyle

**Comment by dvzrv** [comment]
@Albrecht-S btw. how are things coming along for this pull request?

**Comment by Albrecht-S** [comment]
@KBentley57, @dvzrv Sorry for the long delay. I'm now going to work on this issue and I'll keep you informed about any progress. I'll also take a look at fltk-config.

**Comment by Jacalz** [comment]
Any news on the state of this Pull Request?

**Comment by Albrecht-S** [comment]
Sorry, too much other work. :-(
I worked on it, found some issues, tried to improve it, and got distracted by other work...
Before you ask: I can't tell which issue I found, so please be patient.

I'll come back to this issue (PR). Certainly. But please don't hold your breath.

**Comment by dvzrv** [comment]
I have rebased these changes on current master, fixed a few smaller issues, squashed the commits and amended the commit message to be more useful and descriptive (I hope). Please merge at your earliest convenience!

**Comment by dvzrv** [comment]
@Albrecht-S ping :)

**Comment by Albrecht-S** [comment]
@dvzrv pong :)
I'm working on an alternative solution in another context (general CMake update). I didn't forget it, and I'm comparing the given proposal with mine. I'll post an update soon. Thanks for your patience.

In a nutshell: the file names will be fixed as suggested (no `_SHARED` suffix), but the static (CMake) target names will be kept w/o the `_STATIC` suffix. This is mainly for compatibility with previous versions.

**Comment by dvzrv** [comment]
Hm, maybe I remember this wrong, but all the static libs did not have a `_STATIC` file suffix.
The problem was that we had `mylib.a` and `mylib_SHARED.so` and not `mylib.a` and `mylib.so`.

**Comment by dvzrv** [comment]
@Albrecht-S for comparison:

building from master with patch applied and using `-DOPTION_BUILD_SHARED_LIBS=ON`:

```
drwxr-xr-x root/root         0 2020-06-12 12:46 usr/lib/
lrwxrwxrwx root/root         0 2020-06-12 12:46 usr/lib/libfltk.so -> libfltk.so.1.4
lrwxrwxrwx root/root         0 2020-06-12 12:46 usr/lib/libfltk.so.1.4 -> libfltk.so.1.4.0
-rwxr-xr-x root/root   1305000 2020-06-12 12:46 usr/lib/libfltk.so.1.4.0
lrwxrwxrwx root/root         0 2020-06-12 12:46 usr/lib/libfltk_forms.so -> libfltk_forms.so.1.4
lrwxrwxrwx root/root         0 2020-06-12 12:46 usr/lib/libfltk_forms.so.1.4 -> libfltk_forms.so.1.4.0
-rwxr-xr-x root/root     34584 2020-06-12 12:46 usr/lib/libfltk_forms.so.1.4.0
lrwxrwxrwx root/root         0 2020-06-12 12:46 usr/lib/libfltk_gl.so -> libfltk_gl.so.1.4
lrwxrwxrwx root/root         0 2020-06-12 12:46 usr/lib/libfltk_gl.so.1.4 -> libfltk_gl.so.1.4.0
-rwxr-xr-x root/root    177592 2020-06-12 12:46 usr/lib/libfltk_gl.so.1.4.0
lrwxrwxrwx root/root         0 2020-06-12 12:46 usr/lib/libfltk_images.so -> libfltk_images.so.1.4
lrwxrwxrwx root/root         0 2020-06-12 12:46 usr/lib/libfltk_images.so.1.4 -> libfltk_images.so.1.4.0
-rwxr-xr-x root/root    135952 2020-06-12 12:46 usr/lib/libfltk_images.so.1.4.0
```

* building from master without patch applied and using `-DOPTION_BUILD_SHARED_LIBS=ON`:

```
drwxr-xr-x root/root         0 2020-06-12 12:48 usr/lib/
-rw-r--r-- root/root   2890892 2020-06-12 12:48 usr/lib/libfltk.a
lrwxrwxrwx root/root         0 2020-06-12 12:48 usr/lib/libfltk_SHARED.so -> libfltk_SHARED.so.1.4
lrwxrwxrwx root/root         0 2020-06-12 12:48 usr/lib/libfltk_SHARED.so.1.4 -> libfltk_SHARED.so.1.4.0
-rwxr-xr-x root/root   1305000 2020-06-12 12:48 usr/lib/libfltk_SHARED.so.1.4.0
-rw-r--r-- root/root     51506 2020-06-12 12:48 usr/lib/libfltk_forms.a
lrwxrwxrwx root/root         0 2020-06-12 12:48 usr/lib/libfltk_forms_SHARED.so -> libfltk_forms_SHARED.so.1.4
lrwxrwxrwx root/root         0 2020-06-12 12:48 usr/lib/libfltk_forms_SHARED.so.1.4 -> libfltk_forms_SHARED.so.1.4.0
-rwxr-xr-x root/root     34584 2020-06-12 12:48 usr/lib/libfltk_forms_SHARED.so.1.4.0
-rw-r--r-- root/root    320218 2020-06-12 12:48 usr/lib/libfltk_gl.a
lrwxrwxrwx root/root         0 2020-06-12 12:48 usr/lib/libfltk_gl_SHARED.so -> libfltk_gl_SHARED.so.1.4
lrwxrwxrwx root/root         0 2020-06-12 12:48 usr/lib/libfltk_gl_SHARED.so.1.4 -> libfltk_gl_SHARED.so.1.4.0
-rwxr-xr-x root/root    177592 2020-06-12 12:48 usr/lib/libfltk_gl_SHARED.so.1.4.0
-rw-r--r-- root/root    221716 2020-06-12 12:48 usr/lib/libfltk_images.a
lrwxrwxrwx root/root         0 2020-06-12 12:48 usr/lib/libfltk_images_SHARED.so -> libfltk_images_SHARED.so.1.4
lrwxrwxrwx root/root         0 2020-06-12 12:48 usr/lib/libfltk_images_SHARED.so.1.4 -> libfltk_images_SHARED.so.1.4.0
-rwxr-xr-x root/root    135952 2020-06-12 12:48 usr/lib/libfltk_images_SHARED.so.1.4.0
```

This makes me realize, that with this patch currently the static libs don't get installed it seems. Will look into that!

**Comment by Albrecht-S** [comment]
@dzrv: "static libs did not have a _STATIC file suffix": I did neither say nor mean that. ;-)

I edited my previous reply to emphasize CMake **_target names_** which is not equivalent to _output file names_. I only mentioned this because (IIRC) a given patch changed the internal CMake target names for the static lib(s) to `<libname>_STATIC` which is IMHO not appropriate.

So, to summarize and be clear:

- all output filenames won't have any (_SHARED or _STATIC) suffix (the gist of this PR)
- The internal CMake target names differ: no suffix for static (default), _SHARED for the shared libs (built as an option only)

The _CMake target names_ are _exported_ which is useful for user applications that use CMake (`find_package FLTK CONFIG`) to distinguish.

**Comment by dvzrv** [comment]
I understand. I think the weirdness is mainly introduced due to this large macro:

https://github.com/fltk/fltk/blob/e43dee9d8a74fda6325054fc95e99992b8ba5a16/CMake/macros.cmake#L53-L112

I did not want to change or refactor this as I know too little about the intentions around this. Therefore I only patched in "equal naming for all" ;-)

If you have suggestions on how to change it, I can apply those.

**Comment by Albrecht-S** [comment]
As I wrote before I'm working on a general CMake refactoring. Anyway, I took your PR #21, reverted the addition of the _STATIC suffix to the CMake target names, fixed some minor bugs and indenting, and finally renamed some variables to reduce confusion. The existing names were ... exact that: confusing. I hope this is now better, although this is only an intermediate result and work in progress.

Anyway, you can help by pulling branch [pr-21-v2_shared-libs-side-by-side](https://github.com/Albrecht-S/fltk/commits/pr-21-v2_shared-libs-side-by-side) from [my own fork](https://github.com/Albrecht-S/fltk).

I'd appreciate if you could pull this (I rebased everything on current master), test and report your results, i.e. whether it fixes the issue for you or not. I'm very confident it does.

**Comment by Albrecht-S** [comment]
These are the files in lib/ on my Linux system:
```
-rw-r--r--  1 xxx xxx 13138100 Jun 12 20:59 libfltk.a
-rw-r--r--  1 xxx xxx   297046 Jun 12 20:59 libfltk_forms.a
lrwxrwxrwx  1 xxx xxx       20 Jun 12 20:59 libfltk_forms.so -> libfltk_forms.so.1.4
lrwxrwxrwx  1 xxx xxx       22 Jun 12 20:59 libfltk_forms.so.1.4 -> libfltk_forms.so.1.4.0
-rwxr-xr-x  1 xxx xxx   144528 Jun 12 20:59 libfltk_forms.so.1.4.0
-rw-r--r--  1 xxx xxx  1181956 Jun 12 20:59 libfltk_gl.a
lrwxrwxrwx  1 xxx xxx       17 Jun 12 20:59 libfltk_gl.so -> libfltk_gl.so.1.4
lrwxrwxrwx  1 xxx xxx       19 Jun 12 20:59 libfltk_gl.so.1.4 -> libfltk_gl.so.1.4.0
-rwxr-xr-x  1 xxx xxx   598512 Jun 12 20:59 libfltk_gl.so.1.4.0
-rw-r--r--  1 xxx xxx   670904 Jun 12 20:59 libfltk_images.a
lrwxrwxrwx  1 xxx xxx       21 Jun 12 20:59 libfltk_images.so -> libfltk_images.so.1.4
lrwxrwxrwx  1 xxx xxx       23 Jun 12 20:59 libfltk_images.so.1.4 -> libfltk_images.so.1.4.0
-rwxr-xr-x  1 xxx xxx   389456 Jun 12 20:59 libfltk_images.so.1.4.0
lrwxrwxrwx  1 xxx xxx       14 Jun 12 20:59 libfltk.so -> libfltk.so.1.4
lrwxrwxrwx  1 xxx xxx       16 Jun 12 20:59 libfltk.so.1.4 -> libfltk.so.1.4.0
-rwxr-xr-x  1 xxx xxx  5435960 Jun 12 20:59 libfltk.so.1.4.0
```

**Comment by Albrecht-S** [comment]
These are the files in lib/ in my cross-build (MinGW) on Linux:
```
-rw-r--r--  1 xxx xxx 10430840 Jun 12 20:58 libfltk.a
-rwxr-xr-x  1 xxx xxx  7718227 Jun 12 20:58 libfltk.dll
-rw-r--r--  1 xxx xxx  3390016 Jun 12 20:58 libfltk.dll.a
-rw-r--r--  1 xxx xxx   235658 Jun 12 20:58 libfltk_forms.a
-rwxr-xr-x  1 xxx xxx   485426 Jun 12 20:59 libfltk_forms.dll
-rw-r--r--  1 xxx xxx    78172 Jun 12 20:59 libfltk_forms.dll.a
-rw-r--r--  1 xxx xxx  1122400 Jun 12 20:58 libfltk_gl.a
-rwxr-xr-x  1 xxx xxx  1315502 Jun 12 20:59 libfltk_gl.dll
-rw-r--r--  1 xxx xxx   266358 Jun 12 20:59 libfltk_gl.dll.a
-rw-r--r--  1 xxx xxx   534016 Jun 12 20:58 libfltk_images.a
-rwxr-xr-x  1 xxx xxx  2723738 Jun 12 20:59 libfltk_images.dll
-rw-r--r--  1 xxx xxx   483738 Jun 12 20:59 libfltk_images.dll.a
-rw-r--r--  1 xxx xxx  1105160 Jun 12 20:58 libfltk_jpeg.a
-rwxr-xr-x  1 xxx xxx  1302761 Jun 12 20:58 libfltk_jpeg.dll
-rw-r--r--  1 xxx xxx   107124 Jun 12 20:58 libfltk_jpeg.dll.a
-rw-r--r--  1 xxx xxx   950712 Jun 12 20:58 libfltk_png.a
-rwxr-xr-x  1 xxx xxx  1555392 Jun 12 20:58 libfltk_png.dll
-rw-r--r--  1 xxx xxx   292010 Jun 12 20:58 libfltk_png.dll.a
-rw-r--r--  1 xxx xxx   227896 Jun 12 20:58 libfltk_z.a
-rwxr-xr-x  1 xxx xxx   522516 Jun 12 20:58 libfltk_z.dll
-rw-r--r--  1 xxx xxx    61554 Jun 12 20:58 libfltk_z.dll.a
```

Note: the library names, i.e. the linker input library names are different on native Windows (VS build).

Other than that, please keep in mind that this is work in progress.

**Comment by Albrecht-S** [comment]
Please confirm that the recent commit b8318480f5 fixes the issue. If yes we can close this PR.

**Comment by Jacalz** [comment]
I will have a look tomorrow hopefully. This means that we hopefully should finally be able to upgrade the fltk package in Solus 🙂

**Comment by dvzrv** [comment]
@Albrecht-S I built b8318480f and while the installation of the shared libs is correct:

```
drwxr-xr-x root/root         0 2020-06-13 16:03 usr/lib/
lrwxrwxrwx root/root         0 2020-06-13 16:03 usr/lib/libfltk.so -> libfltk.so.1.4
lrwxrwxrwx root/root         0 2020-06-13 16:03 usr/lib/libfltk.so.1.4 -> libfltk.so.1.4.0
-rwxr-xr-x root/root   1305000 2020-06-13 16:03 usr/lib/libfltk.so.1.4.0
lrwxrwxrwx root/root         0 2020-06-13 16:03 usr/lib/libfltk_forms.so -> libfltk_forms.so.1.4
lrwxrwxrwx root/root         0 2020-06-13 16:03 usr/lib/libfltk_forms.so.1.4 -> libfltk_forms.so.1.4.0
-rwxr-xr-x root/root     34584 2020-06-13 16:03 usr/lib/libfltk_forms.so.1.4.0
lrwxrwxrwx root/root         0 2020-06-13 16:03 usr/lib/libfltk_images.so -> libfltk_images.so.1.4
lrwxrwxrwx root/root         0 2020-06-13 16:03 usr/lib/libfltk_images.so.1.4 -> libfltk_images.so.1.4.0
-rwxr-xr-x root/root    135952 2020-06-13 16:03 usr/lib/libfltk_images.so.1.4.0
```

the static libs are not installed.

I have used:

```
 cmake -DCMAKE_INSTALL_PREFIX='/usr' \
        -DCMAKE_INSTALL_LIBDIR='lib' \
        -DCMAKE_BUILD_TYPE='None' \
        -DOPTION_BUILD_SHARED_LIBS=ON \
        -DOPTION_BUILD_EXAMPLES=0 \
        -Wno-dev \
        -B build \
        -S .
make VERBOSE=1 -C build
```
to build. What did you use to achieve the results from your [above post](https://github.com/fltk/fltk/pull/21#issuecomment-643443640)?

**Comment by Albrecht-S** [comment]
@Jacalz please keep in mind though that FLTK 1.4.0 (master) is beta and not released yet. In our (the FLTK development team's) view it's pretty stable, but neither its ABI nor its API are final.

**Comment by Albrecht-S** [comment]
@dvzrv I didn't install the files in my test build, the results I posted are from my build folder.

Thanks for the heads-up that "the static libs are not installed". I'll take a look. If this is true, then it is very likely that it doesn't have to do with the recent changes, i.e. it's not a regression. Maybe it's been that way before (maybe only if both static and dynamic libs are built). I'll check it, but certainly not today; maybe tomorrow...

**Comment by Albrecht-S** [comment]
@dvzrv, regarding installation of static libs:
> What did you use to achieve the results from your above post?

I just did a fresh build and installed everything in a local directory (`CMAKE_INSTALL_PREFIX:PATH=/fltk/temp/1.4/Debug`). I edited the results of `tree | cat -n` to remove irrelevant data (see `...`), but the results here are that all libs (static and shared) get installed as expected. See [attached file](https://github.com/fltk/fltk/files/4776663/i.txt).

I see that you used:
```
 cmake -DCMAKE_INSTALL_PREFIX='/usr' \
        -DCMAKE_INSTALL_LIBDIR='lib' \
```
Please double-check if `CMAKE_INSTALL_LIBDIR='lib'` or anything else causes the issue in your case. I just tried it here and see that the static libs are still installed as expected (after removing the previous installation completely):
```
...
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk.a
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_forms.a
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_images.a
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_gl.a
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk.so.1.4.0
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk.so.1.4
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk.so
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_forms.so.1.4.0
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_forms.so.1.4
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_forms.so
-- Set runtime path of "/fltk/temp/1.4/Debug/lib/libfltk_forms.so.1.4.0" to ""
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_images.so.1.4.0
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_images.so.1.4
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_images.so
-- Set runtime path of "/fltk/temp/1.4/Debug/lib/libfltk_images.so.1.4.0" to ""
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_gl.so.1.4.0
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_gl.so.1.4
-- Installing: /fltk/temp/1.4/Debug/lib/libfltk_gl.so
-- Set runtime path of "/fltk/temp/1.4/Debug/lib/libfltk_gl.so.1.4.0" to ""
...
```
Puzzled...
`cmake version 3.10.2`

**Comment by dvzrv** [comment]
@Albrecht-S My apologies, I didn't have time the past few days.

I have now figured out, that it was just me failing to use our own package tooling...
We have a default policy of stripping staticlibs if a shared lib counterpart exists. I just forgot to switch to the correct option in the build script...

So all is good, and the files can get installed properly side-by-side!

```
drwxr-xr-x root/root         0 2020-06-17 18:43 usr/lib/
-rw-r--r-- root/root   2892278 2020-06-17 18:43 usr/lib/libfltk.a
lrwxrwxrwx root/root         0 2020-06-17 18:43 usr/lib/libfltk.so -> libfltk.so.1.4
lrwxrwxrwx root/root         0 2020-06-17 18:43 usr/lib/libfltk.so.1.4 -> libfltk.so.1.4.0
-rwxr-xr-x root/root   1305000 2020-06-17 18:43 usr/lib/libfltk.so.1.4.0
-rw-r--r-- root/root     51506 2020-06-17 18:43 usr/lib/libfltk_forms.a
lrwxrwxrwx root/root         0 2020-06-17 18:43 usr/lib/libfltk_forms.so -> libfltk_forms.so.1.4
lrwxrwxrwx root/root         0 2020-06-17 18:43 usr/lib/libfltk_forms.so.1.4 -> libfltk_forms.so.1.4.0
-rwxr-xr-x root/root     34584 2020-06-17 18:43 usr/lib/libfltk_forms.so.1.4.0
-rw-r--r-- root/root    225492 2020-06-17 18:43 usr/lib/libfltk_images.a
lrwxrwxrwx root/root         0 2020-06-17 18:43 usr/lib/libfltk_images.so -> libfltk_images.so.1.4
lrwxrwxrwx root/root         0 2020-06-17 18:43 usr/lib/libfltk_images.so.1.4 -> libfltk_images.so.1.4.0
-rwxr-xr-x root/root    135952 2020-06-17 18:43 usr/lib/libfltk_images.so.1.4.0
```

Thanks again for spending some time on this. I'll close this pull-request in favor of your added modifications!

**Comment by Albrecht-S** [comment]
Thanks for your feedback...

und Grüße nach Berlin ;-)

**Pull request closed without merging**
