### PR TITLE
Fluid: enhancement for widget_class for extra option: reposition-and-rescale

### PR DESCRIPTION
**Pull request by etorth**
A refined version of #477 

When using widget_class, in containing window or Fl_Group, we put a Fl_Box as placeholder with a ```xywh```.
And for the widget_class current fluid generates ```xywh```, but when the width and height is bigger than Fl_Box's width and height, there is no auto-rescaling. then event like click outside Fl_Box's ```xywh``` get lost.

fluid currently has the reposition choice but which only handles ```xy``` of given ```xwyh```, there is not rescaling to handle ``wh``` part.

This PR changes the ```Relative``` button into a choice with three option: ```None```/```Relative```/```Relative & Rescale```.
When choose ```None``` or ```Relative```, everything is same with previous version, but when choice ```Relative & Rescale```, the generated code will hand the rescaling issue.

take following widget_class as example:

image

code generated with reposition, but no rescaling:

```cxx
QD_CondChecker_hasItem::QD_CondChecker_hasItem(int X, int Y, int W, int H, const char *L)
  : Fl_Group(0, 0, W, H, L) {
{ Fl_Box* o = new Fl_Box(0, 0, 115, 25, "Has");
  o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
} // Fl_Box* o
{ m_input = new Fl_Value_Input(115, 0, 45, 25);
  m_input->labeltype(FL_NO_LABEL);
} // Fl_Value_Input* m_input
{ Fl_Box* o = new Fl_Box(160, 0, 50, 25, "Item");
  o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
} // Fl_Box* o
{ Fl_Choice* o = new Fl_Choice(210, 0, 145, 25);
  o->down_box(FL_BORDER_BOX);
  o->labeltype(FL_NO_LABEL);
  o->menu(menu_);
} // Fl_Choice* o
position(X, Y);
end();
resizable(this);
}
```

code generated with rescaling:

```cxx
QD_CondChecker_hasItem::QD_CondChecker_hasItem(int X, int Y, int W, int H, const char *L) :
  Fl_Group(0, 0, W, H, L)
{
  { Fl_Box* o = new Fl_Box(round(W*0.000000), round(H*0.000000), round(W*0.323944), round(H*1.000000), "Has");
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
  } // Fl_Box* o
  { m_input = new Fl_Value_Input(round(W*0.323944), round(H*0.000000), round(W*0.126761), round(H*1.000000));
    m_input->labeltype(FL_NO_LABEL);
  } // Fl_Value_Input* m_input
  { Fl_Box* o = new Fl_Box(round(W*0.450704), round(H*0.000000), round(W*0.140845), round(H*1.000000), "Item");
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
  } // Fl_Box* o
  { Fl_Choice* o = new Fl_Choice(round(W*0.591549), round(H*0.000000), round(W*0.408451), round(H*1.000000));
    o->down_box(FL_BORDER_BOX);
    o->labeltype(FL_NO_LABEL);
    o->menu(menu_);
  } // Fl_Choice* o
  position(X, Y);
  end();
  resizable(this);
}
```

I use this change in my daily work, should be safe as a PR.

### CODE REVIEW

**Comment by Albrecht-S** [comment]
Thanks for this PR. Note that I'm not the developer of `fluid` and I'm not particularly familiar with the code you want to change.

1. That said, I would prefer not to have to `#include <math.h>` in favor of doing integer math, if possible. Do you think this could be possible? Note that Fl_Group::resize() works w/o the need of `math.h`.

2. I don't fully understand what you describe in your post and what exactly you want to achieve. Could you please provide a simple but complete example consisting of **only** a `.fl` file that can be compiled and built to a full executable, i.e. it should include a `main()` function. Please do also describe what we need to do to see the effect you like to achieve and how it works w/o your patch - or in this case, which widget attribute should be changed from `Relative & Rescale` to `Relative` to see how it does NOT work as you intend.

This would be helpful to understand the issue, what you want to achieve, and to test your PR. Thanks in advance.

**Comment by etorth** [comment]
Thanks for response, hope this "feature" to be accepted in some way if not a bug in other person's view.
following ```test.fl``` should be sufficient to demonstrate the purpose of this PR:
```cxx
# data file for the Fltk User Interface Designer (fluid)
version 1.0400
header_name {.h}
code_name {.cxx}
widget_class Test_widget_class {open
  xywh {695 274 529 35} box UP_BOX resizable visible position_relative
} {
  Fl_Button {} {
    label b_1
    callback {printf("b_1 clicked\\n");}
    xywh {0 0 105 35}
  }
  Fl_Button {} {
    label b_2
    callback {printf("b_2 clicked\\n");}
    xywh {425 0 105 35}
  }
}

Function {main()} {open return_type int
} {
  Fl_Window m_window {open
    xywh {680 247 565 202} type Double resizable visible
  } {
    Fl_Box {} {
      label Test_widget_class
      xywh {10 25 325 55} box UP_FRAME resizable
      class Test_widget_class
    }
  }
  code {m_window->show();
return Fl::run();} {}
}
```

with above ```test.fl```, it's using the ```Relative``` option to the customized widget class ```Test_widget_class```, and can be compiled by the ```fluid``` ***without*** my PR, and generates following GUI:

image

You can see the ```x``` and ```y``` offset get aligned to the placeholder of ```Test_widget_class```, however the size ```w``` and ```h``` doesn't, which make the ```b_2``` can not be clicked.

Now with the same ```test.fl```, but change the ```Relative``` to ```Relative & Rescale``` as following, you ***need*** my patch to change current ```Fl_Light_Button``` to a ```Fl_Choice```:

image

Now generate the code and build/run the GUI, you can see the widget class ```Test_widget_class``` get auto-rescaled when put into the placeholder:

image


PS:
I did try to call ```Fl_Group::resize(X, Y, W, H)``` as following in the generated ```test.cxx``` code, either in the constructor of the customized widget class, or after the widget instance creation, but neither worked.

```cxx
// generated by Fast Light User Interface Designer (fluid) version 1.0400

#include "test.h"

void Test_widget_class::cb_b_1_i(Fl_Button*, void*) {
  printf("b_1 clicked\n");
}
void Test_widget_class::cb_b_1(Fl_Button* o, void* v) {
  ((Test_widget_class*)(o->parent()))->cb_b_1_i(o,v);
}

void Test_widget_class::cb_b_2_i(Fl_Button*, void*) {
  printf("b_2 clicked\n");
}
void Test_widget_class::cb_b_2(Fl_Button* o, void* v) {
  ((Test_widget_class*)(o->parent()))->cb_b_2_i(o,v);
}

Test_widget_class::Test_widget_class(int X, int Y, int W, int H, const char *L) :
  Fl_Group(0, 0, W, H, L)
{
  this->box(FL_UP_BOX);
  { Fl_Button* o = new Fl_Button(0, 0, 105, 35, "b_1");
    o->callback((Fl_Callback*)cb_b_1);
  } // Fl_Button* o
  { Fl_Button* o = new Fl_Button(425, 0, 105, 35, "b_2");
    o->callback((Fl_Callback*)cb_b_2);
  } // Fl_Button* o
  position(X, Y);
  end();
  resizable(this);
  resize(X, Y, W, H); // <-------------------------------- tried 1, to resize here
}

Fl_Double_Window *m_window=(Fl_Double_Window *)0;

int main() {
  { m_window = new Fl_Double_Window(565, 202, "FLTK-Test_widget_class");
    { Test_widget_class* o = new Test_widget_class(10, 25, 325, 55, "Test_widget_class");
      o->box(FL_UP_FRAME);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(Fl_Align(FL_ALIGN_CENTER));
      o->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(o);
      o->resize(o->x(), o->y(), o->w(), o->h());  // <------------------------------ tried 2: to resize here
    } // Test_widget_class* o
    m_window->end();
  } // Fl_Double_Window* m_window
  m_window->show();
  return Fl::run();
}
```

**Comment by Albrecht-S** [comment]
@etorth Thank you very much for your test code and the description.

**_What I did (abstract):_**
1. I tested your code (.fl) with the original fluid and found the "bug" in your .fl file
2. I fixed your .fl file for usage with the original fluid
3. Conclusion
4. Hint: I propose to use the new `Fl_Flex` class as an alternative for what you likely wanted to achieve.

**_Details:_**

1. The "fault" in your .fl file is that you create the widget with another (**smaller!**) size than the designed size. Thus the second button appears outside the group which makes it "unclickable", as you already know (this is what your patch would change). Later resizing doesn't help, obviously.

2. The solution with the original fluid is to create the group **in the exact size it was designed for** and then resize it to the desired size. This looks a little confusing but it is a possible solution with the original fluid. No need to patch. Here is my working solution:

[pr-481_resize_rescale_v3.fl.txt](https://github.com/fltk/fltk/files/9333563/pr-481_resize_rescale_v3.fl.txt)

Except adding test statements I gave all the relevant widgets names (or renamed them): `b1`, `b2`, and `tc` (the _test_widget_class_ instance). In the generated code you'll notice the following main changes (explained here by comments):
```C++
    { Test_widget_class* o = tc = new Test_widget_class(10, 25, 530, 35, "Test_widget_class");
      // use "original" size of class (530 x 35) in constructor
      tc->box(FL_UP_FRAME);
      // ... some code elided ...
      Fl_Group::current()->resizable(tc);
      // resize the widget to desired size (below):
      o->size(325, 55);
    } // Test_widget_class* tc
```
 3. Conclusion: there is no need to patch fluid to do what you want to achieve. Admittedly, it would be "nice to have" to define a new class and to be able to create an instance in an arbitrary size and position. However, I'm not sure if fluid should be used to do it in the way you propose. I tend not to include your PR because it's not strictly necessary. However, I'm open for arguments.
 
4. That said, the new `Fl_Flex` widget can be used to achieve what you showed in your example. I copied your `.fl` file and modified it to use the new `Fl_Flex` class and derived my own `flex` class similar to what you did. The result is shown in an application that creates three `flex` instances (flex1, flex2, flex3) in different sizes. But note that Fl_Flex is brand-new and has no built-in fluid support yet. My fluid file is just a quick hack, it could maybe be done better and I hope that we will also get fluid support of Fl_Flex soon. Note that I made a design decision to make the buttons in two different widths (b1: 100, b2: 80) and the floating box in the middle gets the remaining size. Here is my fluid file that uses three instances of the class `flex` derived from `Fl_Flex`. Enjoy!

```
# data file for the Fltk User Interface Designer (fluid)
version 1.0400
header_name {.h}
code_name {.cxx}
widget_class flex {open selected
  xywh {168 274 530 35} box THIN_DOWN_BOX resizable
  code0 {type(Fl_Flex::HORIZONTAL);}
  class Fl_Flex visible
} {
  Fl_Button b1 {
    label b1
    callback {printf("b1 clicked\\n");
printf("b1 = (%d, %d, %d, %d)\\n", b1->x(), b1->y(), b1->w(), b1->h());
printf("b2 = (%d, %d, %d, %d)\\n", b2->x(), b2->y(), b2->w(), b2->h());}
    xywh {0 0 105 35}
    code0 {((Fl_Flex *)(o->parent()))->set_size(o, 100);}
  }
  Fl_Box {} {
    comment {invisible spacing}
    xywh {125 0 280 35}
  }
  Fl_Button b2 {
    label b2
    callback {printf("b2 clicked\\n");
printf("b1 = (%d, %d, %d, %d)\\n", b1->x(), b1->y(), b1->w(), b1->h());
printf("b2 = (%d, %d, %d, %d)\\n", b2->x(), b2->y(), b2->w(), b2->h());}
    xywh {425 0 105 35}
    code0 {((Fl_Flex *)(o->parent()))->set_size(o, 80);}
  }
}

Function {main()} {open return_type int
} {
  Fl_Window m_window {
    label {Fluid Test Fl_Flex} open
    xywh {344 74 500 202} type Double resizable visible
  } {
    Fl_Box flex1 {
      label flex1
      xywh {10 25 480 35} box UP_FRAME
      class flex
    }
    Fl_Box flex2 {
      label flex2
      xywh {120 75 280 35} box UP_FRAME
      class flex
    }
    Fl_Box flex3 {
      label flex3
      xywh {50 130 400 60} box UP_FRAME resizable
      class flex
    }
  }
  code {m_window->show();
m_window->size_range(500, 240);
return Fl::run();} {}
}
```

Finally, there's another "flexible" widget `Fl_Grid` I'm working on now which will give us even more flexibility in grouping widgets in rows and columns (i.e. in a grid) without strict pixel positions.

Final note: I did not test your patch/PR because I found a working solution. As said above, there's still room for discussion.

**Comment by etorth** [comment]
@Albrecht-S 

I tested your ```.fl``` and looks the ```Fl_Flex``` can do what I exactly want, thanks!
A widget more friendly to arbitrary ```xywh``` is convenient, like in following situation:

1) users in a team defines many types of widget class individually, in many files, like:
```shell
widget_class_derived_1.fl
widget_class_derived_2.fl
widget_class_derived_3.fl
widget_class_derived_4.fl
...
```

2) another person write an ```mainwindow``` gui can dynamically load one of above widget class. In the ```mainwindow.fl``` it can not know what's the exact size (or size range) that all thoese ```widget_class_derived_<n>``` would have, because it's not written by him/her, the ```mainwindow.fl``` reserves a fixed size room and hope ```widget_class_derived_<n>``` can work well in the room. and can rescale if ```widet_class_derived_<n>``` has bigger size than reserved room.

Hope I expressed clear enough to be understood, for now I will migrate to use ```Fl_Flex```.

**Comment by Albrecht-S** [comment]
@etorth Yes, thank you for this additional scenario which is a good point. It could also be useful for other widgets (groups) that are not just one row or column and can thus not use Fl_Flex. In the near future Fl_Grid will give us even more options.

That said, I'm not going to merge your request now because I'm not sure about all the code changes. Our fluid specialist @MatthiasWM may hopefully chime in and decide whether your PR should be merged or modified in any way. Thank you for all your work on this and for the helpful discussion.

Summary, from my point of view:
- the proposal could be a useful feature for some cases.
- including math.h and using round() should be avoided if possible
- I did not test the actual patch/PR, this needs to be done
- hence I don't know if there would be any side effects

@MatthiasWM Matthias, what do you think, should we merge it?

**Comment by Albrecht-S** [comment]
@etorth Please don't mix different issues in one PR. Adding SVG support is another topic and should not be included in this PR.

Please create **another branch** in your fork and open another PR for SVG support which could then be merged independently of this PR (I'd like to do this, BTW).

Note: It is generally recommended to create a separate branch for every issue you want to merge. You don't need to pull the latest changes into your branches, you can let them as-is which makes merging for the maintainers easier (less confusing). If need be, then we prefer rebasing your branch rather than pulling the changes from upstream/master (fltk) into your branch (downstream).

Thank you.

**Comment by etorth** [comment]
Oops, I didn't realize my latest change updates this PR.
Yes I am in need of the SVG support so I implement it and pushed to my fork, no aware it goes into this PR.

Let me change it.

**Comment by Albrecht-S** [comment]
> Let me change it.

If this helps, I suggest the following:
1. Create a new branch for SVG support in fluid, add your commit, push this to your fork, and make a PR.
2. Create a new branch for your reposition-and-rescale proposal. Use `git cherry-pick` or some other technique to pull your commits from your `master` branch. Then `git rebase -i` (and squash) your branch on top of `upstream/master` [1] so it contains only one commit with your changes. Finally make a new PR from this branch.
3. Optional: create a new branch for your development. Copy/merge whatever you need and work only on this branch for your own development.
4. Finally restore your fork's `master` branch to `upstream/master` [1] and leave it always in sync with our original (`upstream`) master branch.
5. Don't forget to close this PR after you created two new PR's and leave a comment why you closed it with a ref to the new PR(s).

When your PR(s) get merged you can pull from `upstream/master` and `git rebase` your development branch on top of it and continue...

[1] assuming `upstream` is the remote name of the original FLTK repository.

**Comment by Albrecht-S** [comment]
FTR: I missed that you already created PR #489 for svg support in fluid, thanks for that.

**Comment by etorth** [comment]
close this and continue with #497

**Comment by MatthiasWM** [comment]
Continued in #531

**Pull request closed without merging**
