### PR TITLE
Fix MSVC compiler warnings

### PR DESCRIPTION
**Pull request by fire-eggs**
Built for Windows x64 and Win32 release targets.
Built for Linux Mint (gcc 9.3.0) release target.
Executables exercised on Windows 7 x64 and Linux Mint x64.

### CODE REVIEW

**Comment by Albrecht-S** [comment]
Thank you very much, I'm going to (rebase, squash and) merge this PR after a quick test. Diffs look good IMHO.

Just for curiosity: Which Windows compiler/version did you use? FYI: I'm currently using VS-2019, usually with Debug target.

**Comment by Albrecht-S** [comment]
I squashed and merged this PR manually.

It should get status "merged" but I can't do that now. Closing this PR.

Thanks for your contribution!

**Comment by fire-eggs** [comment]
OK, since I've not screwed up badly here, I'll tackle some other ones.

>Just for curiosity: Which Windows compiler/version did you use? FYI: I'm currently using 
>VS-2019, usually with Debug target.

VS-2019 Pro V16.10.4 with MinSizeRel as the target (x64 and Win32 in separate instances).

**Comment by Albrecht-S** [comment]
Great, thanks!
Please drop a note @ #109 regarding which ones you're working on to avoid duplicate work.

Oh, and please use another branch than master (e.g. `issue-109` or something more specific) for your commits/PR. This is easier to handle than master if `origin/master` gets some commits inbetween.

TIA.

**Pull request closed without merging**
